[package]
name = "rsquery"
version = "0.1.0"
authors = ["importcjj <importcjj@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
html5ever = "0.25.1"
markup5ever_rcdom = "0.1.0"
selectors = "0.22.0"
cssparser = "0.27.2"
tendril = "0.4.1"
markup5ever = "0.10.0"

[dev-dependencies]
reqwest = { version = "0.10.4", features = ["blocking"] }
